version: '3.8'
services:
  frontend:
     build:
      context: ./frontend
#      container_name: frontend
     ports:
       - "5001:5001"
     environment:
       FLASK_ENV: development
       MYSQL_HOST: db
       MYSQL_USER: root
       MYSQL_PASSWORD: root

       MYSQL_DB: myflaskapp
     networks:
      - backend

  microusers:
     build:
      context: ./microusers
      #container_name: microusers
     ports:
       - "5002:5002"
     environment:
       FLASK_ENV: development
       MYSQL_HOST: db
       MYSQL_USER: root
       MYSQL_PASSWORD: root
       MYSQL_DB: myflaskapp
     networks:
       - backend

  # microproducts:
  #   build:
  #     context: ./microProducts
  #   container_name: microproducts
  #   ports:
  #     - "5003:5003"
  #   environment:
  #     FLASK_ENV: development
  #     MYSQL_HOST: db
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: root
  #     MYSQL_DB: myflaskapp
  #   networks:
  #     - backend

  # microorders:
  #   build:
  #     context: ./microOrders
  #   container_name: microorders
  #   ports:
  #     - "5004:5004"
  #   environment:
  #     FLASK_ENV: development
  #     MYSQL_HOST: db
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: root
  #     MYSQL_DB: myflaskapp
  #   networks:
  #     - backend

  db:
    image: mysql:8.0
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myflaskapp
    volumes:
      - db_data:/var/lib/mysql
    networks:

      - backend

networks:
  backend:

volumes:
  db_data:
